### ISSUE TITLE
Import tbz

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/relion2#17]
Add tbz and multiple input directory support to gui.

**Comment by darthweider** [comment]
![screen shot 2017-02-08 at 5 21 07 pm](https://cloud.githubusercontent.com/assets/7080816/22760078/ff279694-ee22-11e6-8c57-3ad03bf81b33.png)

Above GUI option will run this command:


 ++++ Executing new job on Tue Feb  7 22:14:36 2017
 ++++ with the following command(s): 
relion_star_loopheader rlnMicrographName > Import/job001/micrographs.star
ls Micrographs/*.mrc >> Import/job001/micrographs.star
 ++++ 



Just need to modify it so that there is a drop-down option for .tbz files; and then create a star file that says 'rlnMicrographMovieName' or such. Maybe something like 'rlnTarName' might be a better name so it's not confused with a star file listing a stack of frames, but we'll also need to change unblur_tbz.py to look for that name.

**Comment by darthweider** [comment]
@a-re  @kuybeda 

There is an even quicker fix. Just replace the name of node-type 0, "2D micrograph movies (*.mrcs)" with "archived micrograph movies (*.tbz)"

Originally, the Motion correction module took .mrcs files as input, but since we have replaced it with unblur_tbz, we have effectively deprecated .mrcs micrograph movie files in favor of .tbz files.

If you just replace the name of the node, the node behavior will work exactly how we want it to. :) 

![screen shot 2017-03-03 at 10 04 13 am](https://cloud.githubusercontent.com/assets/7080816/23556089/4eff5318-fff9-11e6-882e-eecfe471681e.png)

**Comment by a-re** [comment]
That was the plan, I looked at the code and the only difference between the
nodes is the file extension. I will have the changes pushed by tonight,
along with the sourcing changes we discussed yesterday

**Comment by kuybeda** [comment]
We still would like to have the previous option to be backward compatible.
I think that duplicating code and changing it should be also
straightforward. Your thoughts?

**Comment by a-re** [comment]
That would be fine, the region code is very modular so it's only a few
lines of code to add another node type.

**Comment by darthweider** [comment]
Ok. Ideally, the input field in the Unblur_Tbz module should also look for the new node-type, and not node-type 0.

e.g. currently, if you hit the "browse" button, it'll automatically show you only node-type 0 jobs. Obviously, the user can escape out to the project directory if they find themselves in the wrong node, but that's pretty user-unfriendly, especially for people who don't know what's going on with the nodes.
![screen shot 2017-03-03 at 10 56 25 am](https://cloud.githubusercontent.com/assets/7080816/23558024/1e9d4598-0000-11e7-8117-268042f17080.png)

**Comment by a-re** [comment]
Good catch, I will fix that in the commit tonight.

**Comment by kuybeda** [comment]
Has this issue been resolved so far?

**Comment by a-re** [comment]
Done in latest commits. I just added a new node type that represents tbz compressed images, so we still maintain backwards compatibility like Oleg was saying.
