### ISSUE TITLE
standalone gctf options

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/relion2#29]
1) run gctf on a separate micrograph and make sure that the output is ok. 

2) provide required params list for GUI refactoring

3) enable phase flip option and identify naming and location of phase flipped micrograph

**Comment by darthweider** [comment]
1. Stand-alone gctf works.
Run a command such as`/shared/apps/Gctf/Gctf_v1.06/bin/Gctf-v1.06_sm_30_cu8.0_x86_64 Movies/Csy_dsDNA_20161213_0001_movie_avg.mrc --apix 0.413 --do_phase_flip`


2. Required params
--apix 0.413
--kv 300
--cs 2.7
--ac 0.1
--dstep 14 [NOT PROVIDED IN RELION GUI, NEED TO CHANGE FROM DEFAULT]
--boxsize 1024
--resL 50
--resH 4
--defL 5000
--defH 90000
--defS 500
--astm 1000

Aside from dstep, all of these already have fields in the Relion GUI.


3. Phase flipping

`--do_phase_flip` will turn on phase flipping

All per-micrograph output (.log files, .ctf spectrum, _pf.mrc phase-flipped micrographs) will be written in the same directory as the input file. A single micrographs_ctf.star file will be written to the location you are running Gctf from.

My suggestion would be that once the GUI creates a job folder, do something like
cd jobXXX/
mkdir Micrographs/
ln -s /raw_data/*.mrc  ./Micrographs/ 
/path/to/gctf/bin/gctf [--options] ./Micrographs/*.mrc

That way, all per-micrograph information will be written out to jobXXX/Micrographs/, and the summary micrographs_ctf.star file will be written in jobXXX

(It'll be a little more involved because you'll have to only pull the micrographs listed in the input, but that's the basic idea)

**Comment by kuybeda** [comment]
Thanks! What is the meaning of dstep=14. I remember that relion sets it to
that value internally and then it gets output as pixel size in the final
star file with CTF parameters. Can you please share your .ctf file?
