### ISSUE TITLE
Test autosize_mrc

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#36]
Use a reference of an incorrect pixel size and box size to make sure it works

Check that absolute grayscale does not change

**Comment by darthweider** [comment]
I checked the relion_image_handler program, which is what the autosize script calls. Looks like the intensity scale remains the same:


Original
````
header 3d-ref_Csy-AcrF2_flipz_1.097apix_256px.mrc 

 RO image file on unit   1 : 3d-ref_Csy-AcrF2_flipz_1.097apix_256px.mrc     Size=      65537 K

 Number of columns, rows, sections .....     256     256     256
 Map mode ..............................    2   (32-bit real)              
 Start cols, rows, sects, grid x,y,z ...    0     0     0     256    256    256
 Pixel spacing (Angstroms)..............   1.097      1.097      1.097    
 Cell angles ...........................   90.000   90.000   90.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................    0.000       0.000       0.000    
 Minimum density ....................... -0.15900E-01                           
 Maximum density .......................  0.58010E-01                           
 Mean density .......................... -0.90456E-04                           
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .        0        0        0        0
````

Upscaled
````
 RO image file on unit   1 : 3d-ref_Csy-AcrF2_flipz_0.826Apx_384px.mrc     Size=     221185 K

 Number of columns, rows, sections .....     384     384     384
 Map mode ..............................    2   (32-bit real)              
 Start cols, rows, sects, grid x,y,z ...    0     0     0     384    384    384
 Pixel spacing (Angstroms)..............  0.8260     0.8260     0.8260    
 Cell angles ...........................   90.000   90.000   90.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................  -0.8260     -0.8260     -0.8260    
 Minimum density ....................... -0.15900E-01                           
 Maximum density .......................  0.58010E-01                           
 Mean density .......................... -0.90456E-04                           
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .        0        0        0        0
````

Downscaled
````
 RO image file on unit   1 : 3d-ref_Csy-AcrF2_flipz_1.239apix_256px.mrc     Size=      65537 K

 Number of columns, rows, sections .....     256     256     256
 Map mode ..............................    2   (32-bit real)              
 Start cols, rows, sects, grid x,y,z ...    0     0     0     256    256    256
 Pixel spacing (Angstroms)..............   1.239      1.239      1.239    
 Cell angles ...........................   90.000   90.000   90.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................   -1.239      -1.239      -1.239    
 Minimum density ....................... -0.15900E-01                           
 Maximum density .......................  0.58010E-01                           
 Mean density .......................... -0.90456E-04                           
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .        0        0        0        0
````

**Comment by kuybeda** [comment]
It may help though to verify that actual pixel values match those ranges.
You can use Chimera or imod for that.

On Apr 5, 2017 7:09 PM, "darthweider" <notifications@github.com> wrote:

I checked the relion_image_handler program, which is what the autosize
script calls. Looks like the intensity scale remains the same:

Original

header 3d-ref_Csy-AcrF2_flipz_1.097apix_256px.mrc

 RO image file on unit   1 :
3d-ref_Csy-AcrF2_flipz_1.097apix_256px.mrc     Size=      65537 K

 Number of columns, rows, sections .....     256     256     256
 Map mode ..............................    2   (32-bit real)
 Start cols, rows, sects, grid x,y,z ...    0     0     0     256    256    256
 Pixel spacing (Angstroms)..............   1.097      1.097      1.097
 Cell angles ...........................   90.000   90.000   90.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................    0.000       0.000       0.000
 Minimum density ....................... -0.15900E-01
 Maximum density .......................  0.58010E-01
 Mean density .......................... -0.90456E-04
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .        0        0        0        0

Upscaled

 RO image file on unit   1 : 3d-ref_Csy-AcrF2_flipz_0.826Apx_384px.mrc
    Size=     221185 K

 Number of columns, rows, sections .....     384     384     384
 Map mode ..............................    2   (32-bit real)
 Start cols, rows, sects, grid x,y,z ...    0     0     0     384    384    384
 Pixel spacing (Angstroms)..............  0.8260     0.8260     0.8260
 Cell angles ...........................   90.000   90.000   90.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................  -0.8260     -0.8260     -0.8260
 Minimum density ....................... -0.15900E-01
 Maximum density .......................  0.58010E-01
 Mean density .......................... -0.90456E-04
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .        0        0        0        0

Downscaled

 RO image file on unit   1 :
3d-ref_Csy-AcrF2_flipz_1.239apix_256px.mrc     Size=      65537 K

 Number of columns, rows, sections .....     256     256     256
 Map mode ..............................    2   (32-bit real)
 Start cols, rows, sects, grid x,y,z ...    0     0     0     256    256    256
 Pixel spacing (Angstroms)..............   1.239      1.239      1.239
 Cell angles ...........................   90.000   90.000   90.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................   -1.239      -1.239      -1.239
 Minimum density ....................... -0.15900E-01
 Maximum density .......................  0.58010E-01
 Mean density .......................... -0.90456E-04
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .        0        0        0        0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KryoEM/relion2/issues/36#issuecomment-292022971>, or mute
the thread

**Comment by darthweider** [comment]
@kuybeda Looks like autosize crashed -- not quite sure why. It ran individually for each process (which it probably is not supposed to do), and then multiple processes threw errors from Relion about the memory allocation size requested being 0.....

output and error files in /shared/process/guot/Csy/Csy_dsDNA/job089/


Would it be easier to troubleshoot if I gave you an initial model for the sanity test in the "wrong" size?

That way, I can also revert this commit and keep running things for Csy.

**Comment by kuybeda** [comment]
You can specify a specific commit number instead of branchname in
inventory, as opposed to reverting this one.

He problem is probably due to multiple processes trying to write to the
same resized file...

**Comment by darthweider** [comment]
While processing, I also thought that maybe we should also use autosize for any masks that are provided by the user.

I haven't tried using autosize.py on masks before, so I'm not 100% sure it will work, but I don't see why not.

**Comment by kuybeda** [comment]
If the masks have to be binary, i.e. 0 or 1, then autosize may distort
their values especially at the object edges. However, I recall most of the
time there is a soft mask used, so it should be ok to use resize on it.

All this is provided that we are 100% sure that autosize doesn't change
gray-value normalization issues. You are half-way there, so in addition to
seeing that min max range is ok, we still need to see that actual pixel
values are the same-order of magnitude after the resize.

**Comment by darthweider** [comment]
Here are stats on mean/stddev pixel values per slice. The per-slice min, max, mean, and stddev values look about the same when I scan it by eye (right order of magnitude). I don't know if you're thinking of a doing a more rigorous analysis.

[stats_3d-ref_Csy-AcrF2_flipz_1.239apix_256px.txt](https://github.com/KryoEM/relion2/files/903354/stats_3d-ref_Csy-AcrF2_flipz_1.239apix_256px.txt)
[stats_3d-ref_Csy-AcrF2_flipz_1.097apix_256px.txt](https://github.com/KryoEM/relion2/files/903356/stats_3d-ref_Csy-AcrF2_flipz_1.097apix_256px.txt)
[stats_3d-ref_Csy-AcrF2_flipz_0.826Apx_384px.txt](https://github.com/KryoEM/relion2/files/903355/stats_3d-ref_Csy-AcrF2_flipz_0.826Apx_384px.txt)

**Comment by kuybeda** [comment]
This is what I meant to check and this order of magnitude should suffice.
Thanks!

Did you do both rescale and resize? Testing rescale is more critical.

On Apr 6, 2017 12:59 PM, "darthweider" <notifications@github.com> wrote:

Here are stats on mean/stddev pixel values per slice. The per-slice min,
max, mean, and stddev values look about the same when I scan it by eye
(right order of magnitude). I don't know if you're thinking of a doing a
more rigorous analysis.

stats_3d-ref_Csy-AcrF2_flipz_1.239apix_256px.txt
<https://github.com/KryoEM/relion2/files/903354/stats_3d-ref_Csy-AcrF2_flipz_1.239apix_256px.txt>
stats_3d-ref_Csy-AcrF2_flipz_1.097apix_256px.txt
<https://github.com/KryoEM/relion2/files/903356/stats_3d-ref_Csy-AcrF2_flipz_1.097apix_256px.txt>
stats_3d-ref_Csy-AcrF2_flipz_0.826Apx_384px.txt
<https://github.com/KryoEM/relion2/files/903355/stats_3d-ref_Csy-AcrF2_flipz_0.826Apx_384px.txt>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/KryoEM/relion2/issues/36#issuecomment-292238233>, or mute
the thread

**Comment by darthweider** [comment]
Yes, I did both rescale and resize.

**Comment by darthweider** [comment]
Used autosize from the GUI successfully, for model that had to be rescaled.
